from typing import Any, Iterable, Tuple, Union

PrinterInfo = Tuple[int, int, str, Any]

def EnumPrinters(flags: int) -> list[PrinterInfo]: ...

def OpenPrinter(name: str) -> Any: ...

def StartDocPrinter(hprinter: Any, level: int, docinfo: Tuple[str, Any, str]) -> Any: ...

def StartPagePrinter(hprinter: Any) -> Any: ...

def WritePrinter(hprinter: Any, data: bytes) -> Any: ...

def EndPagePrinter(hprinter: Any) -> Any: ...

def EndDocPrinter(hprinter: Any) -> Any: ...

def ClosePrinter(hprinter: Any) -> Any: ...
